@id=45ce052e-dc35-42ba-b871-1eb3fe9e30e3

GET https://localhost:7009/dinners/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjOWUzMmZhYi00YjJkLTQ5NjQtYjBiNy1hNGQzZWRiODg4ZDIiLCJnaXZlbl9uYW1lIjoiU2FtaXIiLCJmYW1pbHlfbmFtZSI6Ik9zbWFub3YiLCJqdGkiOiIyZTg2MTg2Mi1hY2EwLTQ3NWItOWMzNC0xZDJhZjk3NWVlNWIiLCJleHAiOjE2NjcxNzA2MzYsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.XrrjWmsEfp6HT2jt3mA5vF1lFwDWbXJJ9FtkGo0Mr1A